const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
	// 检查是否连接到独立节点
	const network = await ethers.provider.getNetwork();
	console.log(`\nNetwork: ${network.name} (Chain ID: ${network.chainId})`);
	
	// 尝试获取区块号来验证连接
	try {
		const blockNumber = await ethers.provider.getBlockNumber();
		console.log(`Current block: ${blockNumber}`);
	} catch (error) {
		console.error("Cannot connect to network:", error.message);
		process.exit(1);
	}
	
	const [deployer] = await ethers.getSigners();
	console.log("Deployer:", deployer.address);
	
	// 检查部署者余额
	const balance = await ethers.provider.getBalance(deployer.address);
	console.log(`Balance: ${ethers.formatEther(balance)} ETH\n`);

	const supply = ethers.parseUnits("1000000", 18);
	const TestToken = await ethers.getContractFactory("TestToken");
	const tokenA = await TestToken.deploy("TokenA", "TKA", supply);
	const tokenB = await TestToken.deploy("TokenB", "TKB", supply);
	await tokenA.waitForDeployment();
	await tokenB.waitForDeployment();
	
	const tokenAAddress = await tokenA.getAddress();
	const tokenBAddress = await tokenB.getAddress();
	console.log("TokenA:", tokenAAddress);
	console.log("TokenB:", tokenBAddress);

	const DEX = await ethers.getContractFactory("DEX");
	const dex = await DEX.deploy(tokenAAddress, tokenBAddress);
	await dex.waitForDeployment();
	
	const dexAddress = await dex.getAddress();
	console.log("DEX:", dexAddress);
	
	// 获取LP Token地址
	const lpTokenAddress = await dex.lpToken();
	console.log("LPToken:", lpTokenAddress);

	// approve initial liquidity from deployer
	await (await tokenA.approve(dexAddress, ethers.MaxUint256)).wait();
	await (await tokenB.approve(dexAddress, ethers.MaxUint256)).wait();

	// add initial liquidity 10_000 each
	await (await dex.addLiquidity(ethers.parseUnits("10000", 18), ethers.parseUnits("10000", 18))).wait();
	console.log("Initial liquidity added");

	// 生成 .env 文件
	const envContent = `# DEX Contract Addresses (Auto-generated by deploy script)
# Generated at: ${new Date().toISOString()}

# DEX Contract
DEX_ADDRESS=${dexAddress}

# Token Contracts
TOKEN0_ADDRESS=${tokenAAddress}
TOKEN1_ADDRESS=${tokenBAddress}

# LP Token Contract
LP_TOKEN_ADDRESS=${lpTokenAddress}

# Server Configuration
PORT=3001
RPC_URL=http://127.0.0.1:8545

# Network Configuration
CHAIN_ID=31337
CORS_ORIGIN=*
`;

	const envPath = path.join(__dirname, "..", ".env");
	fs.writeFileSync(envPath, envContent);
	console.log("\n.env file generated successfully!");
	console.log("File location:", envPath);
	
	// 同时输出到控制台，方便复制
	console.log("\n" + "=".repeat(60));
	console.log("Contract Addresses Summary:");
	console.log("=".repeat(60));
	console.log(`DEX_ADDRESS=${dexAddress}`);
	console.log(`TOKEN0_ADDRESS=${tokenAAddress}`);
	console.log(`TOKEN1_ADDRESS=${tokenBAddress}`);
	console.log(`LP_TOKEN_ADDRESS=${lpTokenAddress}`);
	console.log("=".repeat(60));
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});

